use gymappdb;

INSERT INTO Users(id, uid, username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (1,'XErraWTEKjSN4PhK2LXTkVsvwRG2','Camurray','camurray','Christopher','Murray','1994-08-11','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/Camurray?alt=media&token=66a52294-e39c-4def-9e8f-22ec706d9446','hipeepzz@yahoo.com','This is a bio',1);
INSERT INTO Users(id,username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (2,'J_Nippard','nippard','Jeff','Nippard','1990-10-06','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/JeffNippard?alt=media&token=483f8e2a-4df2-4158-8653-ba94b19d4bea','Nippard.Jeff@gmail.com','Canadian professional bodybuilder, fitness coach, YouTuber, and powerlifter',2);
INSERT INTO Users(id,username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (3,'Arnie','arnold','Arnold','Schwarzenegger ','1947-7-30','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/Arnie?alt=media&token=6634c836-4b25-44e2-924b-76332031e39f','Arnie47@yahoo.com','Austrian-born American actor, film producer, businessman, retired professional bodybuilder and politician who served as the 38th governor of California between 2003 and 2011',3);
INSERT INTO Users(id,username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (4,'TheKing','coleman','Ronnie','Coleman','1964-05-13','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/ronnie?alt=media&token=a90347c4-0489-4879-b629-688935624fff','King.Coleman@gmail.com','American retired professional bodybuilder. The winner of the Mr. Olympia title for eight consecutive years, widely regarded as either the greatest or one of the two greatest bodybuilders of all time',4);
INSERT INTO Users(id,username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (5,'DogFather','chestnut','Joey','chestnut','1983-06-21','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/Dogfather?alt=media&token=88a2aeb9-71ea-440d-8833-c269fc966bcf','J_Chestnut@gmail.com','Ranked first in the world by Major League Eating. Won the 92nd Annual Nathan\'s Hot Dog Eating Contest, beating six-time defending champion Takeru "Tsunami" Kobayashi by consuming a world record 66 hot dogs and buns in 12 minutes',5);
INSERT INTO Users(id,username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (6,'Cbumstead','cbum','Christopher','Bumstead','1995-02-2','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/Cbumstead?alt=media&token=e64c91a5-9a0a-40b9-ba13-3bf83020e448','CBUM@gmail.com','Canadian IFBB professional bodybuilder and reigning Mr. Olympia Classic Physique winner',6);
INSERT INTO Users(id,username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (7,'Mrs_Shaw','shaw','Andrea','Shaw','1983-12-18','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/Shaw?alt=media&token=5151c9bc-d23f-4858-a155-a3c4e7091bf8','shaw.andrea@gmail.com','I Hold two Ms. Olympia title wins and two Ms Rising Phoenix title wins.',7);
INSERT INTO Users(id,username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (8,'IamThor','thor','Christohper','Hemsworth','1983-08-11','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/IAmThor?alt=media&token=de926271-4bab-42c1-9d88-4158b0fe920c','godofthunder@gmail.com','Yes. It\'s a very, very interesting theory. I have a simpler one. You\'re all not worthy.',12);
INSERT INTO Users(id,username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (9,'SuperCavill','Superman','Henry','Cavill','1983-05-5','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/SuperCavill?alt=media&token=e0a679ec-c30e-4109-b473-ba5418328e51','SuperManCavill@yahoo.com','No matter where you go in life there\'s always going to be the one person that wants to bring you down, so stay strong and face your problems instead of running away.',14);
INSERT INTO Users(id,username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (10,'Jlo','lopez','Jennifer','Lopez','1969-04-24','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/Jlo?alt=media&token=8d0b9a56-81f7-4504-b6b9-260b71b43fe4','Jlopez@yahoo.com',' American singer, actress, and dancer',16);
INSERT INTO Users(id,username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (11,'TheBeast','eHall','Eddie','Hall','1988-01-15','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/Eddiehall?alt=media&token=9131881e-a7d8-4e11-a5a2-d3792bdbf351','thebeast@yahoo.com','Strongest man, actor, boxer...',17);
INSERT INTO Users(id,username,userPassword,firstName,lastName,DoB,imagePath,email,profileBio,currentWeeklyScheduleID) VALUES (12,'TheMountain','thor','Hafþór','Björnsson','1988-11-26','https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/Thor?alt=media&token=c6d86fca-c8c4-4779-9353-c5543f78f29f','The_Mountain@gmail.com','Born Iceland, Genetically strongest man alive, sometimes Mountain sometimes Ser Gregor Clegane',18);
INSERT INTO Users(id, uid, username, userPassword, firstName, lastName, DoB, imagePath, email, profileBio, currentWeeklyScheduleID) VALUES ('13', 'otN4dAUHj9Zxkq5IvpReOkJUyQB2', 'Murraych', 'murray', 'Christopher', 'Murray', '1994-08-11', 'https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/Murraych?alt=media&token=a66da63f-9bfc-4b82-9878-a07ce1b1c01d', 'Chrisware707@gmail.com', 'This is my first workout notebook!!', '22');
INSERT INTO Users(id, uid, username, userPassword, firstName, lastName, DoB, imagePath, email, profileBio, currentWeeklyScheduleID) VALUES ('14', 'mHkAnjkYg1OzmeUGHl8efMtpqAI2', 'AndrewM', '123456', 'Andrew', 'Moir', '2001-02-01', 'https://firebasestorage.googleapis.com/v0/b/gymapp-470.appspot.com/o/AndrewM?alt=media&token=c079fa11-b442-43b2-9726-01795bb3f5a2', 'Andrew@temp.com', 'I didn\'t have time for a bio, gotta hit the gym!', '23');
